name: dotnet package

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test
      - name: Create pkg
        run: dotnet pack -p:PackageVersion=1.0.8
        working-directory: ./context-pkg
      - name: Archive Nuget
        uses: actions/upload-artifact@v3
        with:
          name: pkg
          path: "**/*.nupkg"
      - name: Publish Nuget
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          
      
